version: '3.8'
services:
  matchaker-cache:
    image: redis:7.4-alpine
    restart: always
    ports:
      - '6380:6380'
    command: ["redis-server", "--bind", "matchaker-cache", "--port", "6380", "--requirepass" , "eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"]
volumes:
  matchaker-cache:
    driver: local