version: '3.8'
services:
  cache:
    image: redis:7.4-alpine
    restart: always
    ports:
      - '6380:6380'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
volumes:
  cache:
    driver: local